apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcls.supercluster.glide.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: supercluster.glide.io/v1alpha1
    kind: XCls       
  resources:
    - name: eks-cluster
      base:
        apiVersion: cluster.glide.io/v1alpha1
        kind: XEks
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.resourceConfig.providerConfigName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.resourceConfig.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.resourceConfig.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.accountId
          toFieldPath: spec.resourceConfig.accountId
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.resourceConfig.objectTags
          toFieldPath: spec.resourceConfig.objectTags
        # - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        #   toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.parameters.version
          toFieldPath: spec.parameters.version
        - fromFieldPath: spec.parameters.subnetIds
          toFieldPath: spec.parameters.subnetIds
        - fromFieldPath: spec.parameters.endpointPrivateAccess
          toFieldPath: spec.parameters.endpointPrivateAccess
        - fromFieldPath: spec.parameters.endpointPublicAccess
          toFieldPath: spec.parameters.endpointPublicAccess
        - fromFieldPath: spec.managedNodeGroups.minSize
          toFieldPath: spec.managedNodeGroups.minSize
        - fromFieldPath: spec.managedNodeGroups.maxSize
          toFieldPath: spec.managedNodeGroups.maxSize
        - fromFieldPath: spec.managedNodeGroups.desiredSize
          toFieldPath: spec.managedNodeGroups.desiredSize
        - fromFieldPath: spec.managedNodeGroups.desiredSize
          toFieldPath: spec.managedNodeGroups.desiredSize
        - fromFieldPath: spec.managedNodeGroups.capacityType
          toFieldPath: spec.managedNodeGroups.capacityType
        - fromFieldPath: spec.managedNodeGroups.instanceTypes
          toFieldPath: spec.managedNodeGroups.instanceTypes
        - fromFieldPath: spec.managedNodeGroups.amiType
          toFieldPath: spec.managedNodeGroups.amiType
        - type: ToCompositeFieldPath
          fromFieldPath: status.clusterName
          toFieldPath: status.clusterName
          policy:
            fromFieldPath: Required
      connectionDetails:
        - name: cluster-ca
          fromConnectionSecretKey: clusterCA
        - name: apiserver-endpoint
          fromConnectionSecretKey: endpoint
        - name: kubeconfig
          fromConnectionSecretKey: kubeconfig
    - name: add-cluster-to-loft
      base:
        apiVersion: supercluster.glide.io/v1alpha1
        kind: XHost
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.k8sproviderConfigName
          toFieldPath: spec.resourceConfig.providerConfigName
        - fromFieldPath: status.clusterName
          toFieldPath: spec.parameters.job-Name
          policy:
            fromFieldPath: Required
        - fromFieldPath: status.clusterName
          toFieldPath: spec.resourceConfig.clusterName
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.parameters.loft-domain
          toFieldPath: spec.parameters.loft-domain
        - fromFieldPath: spec.parameters.secretName
          toFieldPath: spec.parameters.secretName
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
   